Net_Metering/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    # domain.com
    
    path('', views.simple_view, name="home"),
    path('admin/', admin.site.urls),

    # domain.com/calculator/
    path('simulation/', include('simulation.urls')),

]

simulation/urls.py
"""
URLS py in the application

Author: Anestis
Date: December, 2023
"""
from django.urls import path
from . import views

# We must stick to lowercase to app_name. Django convention
app_name = 'simulation'

# url routes list
urlpatterns = [
    # path --> domain.com / simulation /
    # /my_apps --> PROJECT urls.py

    path('ajax/', views.calculate_power, name='calculate_power'),
    path('recalculation/', views.recalculate_pv_system_properties, 
         name='recalculate_pv_system_properties'),
    path('addbattery/', views.add_battery, name='add_battery'),
    path('calculator/', views.calculator_form_fields_handler, name='calculator'),
    path('dashboard/', views.dashboard_results, name='dashboard'),
    path('regulations/', views.regulations, name='regulations'),
    path('about/', views.about, name='about'),
    # path('signup/', views.signup, name='signup'),
]

templates/home.html
{% extends "index.html" %}

{% load static %}

{% block title %}
<title>Home</title>
{% endblock %}

{% block menu_list %}
    <li><a class="nav-link active" href="{% url 'home' %}"><i class="fas fa-home"></i> home</a></li>
    <li><a href="{% url 'simulation:calculator' %}"><i class="fas fa-calculator"></i> calculator</a></li>
    <li><a href="{% url 'simulation:dashboard' %}"><i class="fas fa-qrcode"></i> dashboard</a></li>
    <li><a href="{% url 'simulation:regulations' %}"><i class="fas fa-scale-unbalanced-flip"></i> regulations</a></li>
    <li><a href="{% url 'simulation:about' %}"><i class="fas fa-info-circle"></i> about</a></li>
{% endblock %}



{% block body_class %} home-body {% endblock %}
  

{% block content %}

<div class="main-page-content">

  <section class="main-page-section">
       <div class="main-page-article">

          <div class="article-body">
            <h2 class="article-first-title">Το Net metering ως βιώσιμη λύση ενσωμάτωσης Φ/Β συστημάτων
            στο δίκτυο ηλεκτρικής ενέργειας. Μείωση κόστους ηλεκτρικής ενέργειας και υιοθέτηση 
            ανανεώσιμων πηγών ενέργειας.</h2>
             
          </div>

          <div class="article-body" >
            <h2 class="article-big-titles">Τι είναι το Net Metering;</h2>
             Ο ενεργειακός συμψηφισμός αυτοπαραγωγής με ιδιοκατανάλωση, είναι ένας μηχανισμός που επιτρέπει 
            στους κατόχους Φ/Β συστημάτων, να καταναλώνουν την ποσότητα ρεύματος τη στιγμή που παράγεται, 
            καθώς και να επιστρέφουν την πλεονάζουσα ηλεκτρική ενέργεια πίσω στο δίκτυο. Αυτή η ηλεκτρική 
            ενέργεια αποθηκεύεται στο δίκτυο έως ότου απαιτηθεί και μέχρι τα 3 έτη. Αυτό επιτυγχάνεται με 
            έναν μετρητή διπλής κατεύθυνσης, ο οποίος μετρά τόσο την ενέργεια που καταναλώνεται από το δίκτυο 
            όσο και αυτή που παράγεται από το Φ/Β και εγχύεται στο δίκτυο. Ο συμψηφισμός τελικά είναι λογιστικός, 
            στοχεύοντας στη μείωση έως μηδενισμό του λογαριασμού του ρεύματος. Μπορεί να αποδειχθεί εξαιρετικά 
            κερδοφόροw, με ή χωρίς υποστήριξη συστήματος μπαταριών. <strong>Για να δοκιμάσετε τον υπολογιστή προσομοίωσης
            επιλέξτε το "CALCULATOR" στη γραμμή πλοήγησης του ιστότοπου ή τον επόμενο σύνδεσμο: 
             <a href="{% url 'simulation:calculator' %}" class="link-mid-position-home" >
              <i class="fas fa-calculator spacer-text"></i> Υπολογιστής απόδοσης </a></strong>
   

          </div>

          <div class="img-div-home">
            <img class="img-info" src="{% static 'images/Net1.1.png' %}" alt="No Image">
          </div>

          <div class="article-body">
            <h2 class="article-big-titles">Η κερδοφορία του ενεργειακού συμψηφισμού αυτοπαραγωγής εξαρτάται άμεσα από:</h2>

            <ul>
                <li>
                    <h3 class="article-small-titles">Μέγεθος και χωρητικότητα του συστήματος: </h3>
                    Το μέγεθος και η χωρητικότητα του ηλιακού συστήματος επηρεάζουν απευθείας την κερδοφορία του. 
                    Μεγαλύτερα συστήματα μπορούν να παράξουν περισσότερη  ηλεκτρική ενέργεια, μεγιστοποιώντας την 
                    εξοικονόμηση μέσω ενεργειακού συμψηφισμού.
                </li>
                <li>
                    <h3 class="article-small-titles">Ηλιοφάνεια περιοχής εγκατάστασης και προσανατολισμός Φ/Β συστήματος: </h3>
                    Η ποσότητα ηλιακής ακτινοβολίας της περιοχής εγκατάστασης, επηρεάζουν 
                    την παραγωγή ενέργειας του φωτοβολταϊκού συστήματος, άρα την απόδοση του. 
                    Περιοχές με υψηλότερη ηλιακή ακτινοβολία θεωρούνται πιο επωφελείς για την 
                    εγκατάσταση των συστημάτων Net Metering. Επιπλέον, το αζιμούθιο και η κλίσης 
                    των ηλιακών πάνελ είναι σημαντικοί για την απόδοση του συστήματος. Το αζιμούθιο 
                    αναφέρεται στην κατεύθυνση προς την οποία είναι στραμμένο το σύστημα σε σχέση με 
                    τον γεωγραφικό βορρά, ενώ η κλίση αναφέρεται στη γωνία υπό την οποία τα πάνελ 
                    τοποθετούνται ανάλογα με το οριζόντιο επίπεδο. Η ιδανικές ρυθμίσεις για τα 
                    φωτοβολταϊκά πάνελ είναι να έχουν Νότιο προσανατολισμό και κλίση 30°.
                </li>
                <li>
                    <h3 class="article-small-titles">Προφίλ κατανάλωσης ηλεκτρικής ενέργειας: </h3>
                     Ο τρόπος κατανάλωσης της ηλεκτρικής ενέργειας επηρεάζει σημαντικά την κερδοφορία 
                     του ενεργειακού συμψηφισμού αυτοπαραγωγής. Η ευνοϊκή εκμετάλλευση των ωρών αιχμής 
                     παραγωγής ηλιακής ενέργειας επιτρέπει τη μέγιστη ιδιοκατανάλωση και, κατ' επέκταση,
                     μεγαλύτερες εξοικονομήσεις.
                </li>
            </ul>
            
                <div class="img-div-home">
                  <img class="img-equipment" src="{% static 'images/equipment_greek.png' %}" alt="No Image">
                </div>

             <div>
                <h2 class="article-big-titles">Ενσωμάτωση συσσωρευτών για αποθήκευση ενέργειας:</h2>

                <div>Παρόλο που ο ενεργειακός συμψηφισμός αυτοπαραγωγής μπορεί να υλοποιηθεί και χωρίς 
                  την υποστήριξη μπαταριών, η ενσωμάτωση συστημάτων αποθήκευσης ενέργειας προσφέρει 
                  επιπλέον οφέλη. Οι μπαταρίες επιτρέπουν στους κατόχους Φ/Β να αποθηκεύουν ενέργεια, 
                  για την καλυψη βασικών αναγκών του συστήματος, κατά τις ώρες χωρίς ηλιακή παραγωγή
                   ή περίπτωση διακοπής ρεύματος.
                </div>
                  
                        
                   <ul> <h3 class="article-small-titles">Οφέλη</h3>
                    <li>Αύξηση ιδιοκατανάλωσης</li>
                    <li>Εξασφάλιση σταθερότητας παροχής</li>
                    <li>Μείωση εξάρτησης από το δίκτυο</li>
                   </ul>

                   <div class="img-div-home">
                    <img class="img-info" src="{% static 'images/selfConsume2.jpg' %}" alt="No Image">
                  </div>
             </div>
                    <div class="container carousel-border">
                      <h2>Οφέλη Ενσωμάτωσης συσσωρευτών</h2>
                      <div id="myCarousel" class="carousel slide">
                        <!-- Indicators -->
                        <div class="carousel-indicators">
                          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                          <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                        </div>
                    
                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                    
                          <div class="carousel-item active">
                            <img src="{% static 'images/overproducing.jpg' %}" alt="overproducing" style="width:100%;">
                            <div class="carousel-caption">
                              <h3></h3>
                              
                            </div>
                          </div>
                    
                          <div class="carousel-item">
                            <img src="{% static 'images/power_outage2.jpg' %}" alt="power-outage" style="width:100%;">
                            <div class="carousel-caption">
                              <h3></h3>
                              
                            </div>
                          </div>
                        
                          <div class="carousel-item">
                            <img src="{% static 'images/underproducing.jpg' %}" alt="underproducing" style="width:100%;">
                            <div class="carousel-caption">
                              <h3></h3>
                          
                            </div>
                          </div>
                      
                        </div>
                    
                        <!-- Left and right controls -->
                        <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
                          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
                          <span class="carousel-control-next-icon" aria-hidden="true"></span>
                          <span class="visually-hidden">Next</span>
                        </button>
                      </div>
                    </div>
            
             
            
          </div>   

      </div>
  </section>

  </div>

  <div class="spacer"></div>


{% endblock %}

templates/index.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Homepage</title>
    {% endblock %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="website icon" type="png" href="{% static 'images/panel_128x107.png'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css"/>
    <link rel="stylesheet" href=" {% static 'Net_Metering/css/style.css' %}"/>

    {% block css %} 
    {% endblock %}

    <script src="{% static 'Net_Metering/javascript/script.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    {% block script %}
    {% endblock %}

</head>

<body class="{% block body_class %}{% endblock %} ">

        <nav class="main-navbar">

            <div class="main-navbar-right-container">

                <header class="main-header">         
                    <div class="header-container-left">
                        <a href="{% url 'home' %}"><img class="sm-image" src="{% static 'images/panel.png'%}" alt="photo not found"></a>
                        <p class="logo"><a href="{% url 'home' %}">
                          Simulation - <strong style="color: #ed4901;">N</strong>et Metering</a></p>
                    </div>
                </header>
            </div >

            <div class="main-navbar-left-container" id="main-navbar-left-container">
                <input type="checkbox" id="check-navbar">
                <label  for="check-navbar" id="menu-nav-button" class="demo-class"><i class="fas fa-bars"></i></label>

                <ul class="nav-list" id="nav-list">
                    {% block menu_list %}
                    <li><a class="nav-link active" href="{% url 'home' %}"><i class="fas fa-home"></i> home</a></li>
                    <li><a href="{% url 'simulation:dashboard' %}"><i class="fas fa-qrcode"></i> dashboard</a></li>
                    <li><a href="{% url 'simulation:calculator' %}"><i class="fas fa-calculator"></i> calculator</a></li>
                    <li><a href="{% url 'simulation:regulations' %}"><i class="fas fa-scale-unbalanced-flip"></i> regulations</a></li>
                    <li><a href="{% url 'simulation:about' %}"><i class="fas fa-info-circle"></i> about</a></li>
                    {% endblock %}
                </ul>         
                   <div class="header-container-right">
                        {% block color_theme %}
                        
                        {% endblock %}
                       <!-- <p class="signup"><a href="{% url 'simulation:signup' %}" title="Νέα Εγγραφή"><i class="fas fa-user"></i></a></p>
                        <p class="login"><a title="Σύνδεση" data-toggle="modal" data-target="#loginModal"><i class="fas fa-sign-in"></i></a></p> -->
                        
                    </div>     
            </div>
        </nav>
        
        <div id="main-index-content-for-all">
            {% block content %}
                       
            {% endblock %}
        </div>
            
  <footer class="footer">
      <div class="other-links">
          <a href="https://linkedin.com/in/anestis-giannakosian-880707220" title="connection to linkedin"><i class="fab fa-linkedin-in"></i> </a>
          <a href="https://github.com/anegian" title="connection to github"><i class="fab fa-github"></i></a>
          <a href="https://youtube.com" title="connection to youtube"><i class="fab fa-youtube"></i></a>
      </div>
          <span class="admin-info">
              <i class="fas fa-copyright"> 2023 Anestis Giannakosian. All rights reserved</i>
        </span>
  </footer>
</body>
</html>